# Generated by Django 6.0.4 on 2026-04-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['name'], name='candidates_name_2966a8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_at'], name='candidates_created_893b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatlog',
            index=models.Index(fields=['session_id', 'created_at'], name='chat_logs_session_a35c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['created_at'], name='job_descrip_created_a5d3de_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['title'], name='job_descrip_title_869c66_idx'),
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['job', 'rank_position'], name='rankings_job_id_12a6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='ranking',
            index=models.Index(fields=['overall_score'], name='rankings_overall_b1f13e_idx'),
        ),
    ]
