# Generated by Django 6.0.4 on 2026-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auditlog_audit_logs_action_391715_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator')], default='USER', max_length=20),
        ),
    ]
