# Generated by Django 4.2.30 on 2026-08-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_rename_job_descriptions_to_jobs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobdescription',
            new_name='jobs_created_7c32a5_idx',
            old_name='job_descrip_created_a5d3de_idx',
        ),
        migrations.RenameIndex(
            model_name='jobdescription',
            new_name='jobs_title_8402eb_idx',
            old_name='job_descrip_title_869c66_idx',
        ),
        migrations.RenameIndex(
            model_name='jobdescription',
            new_name='jobs_status_92f544_idx',
            old_name='job_descrip_status_7b0350_idx',
        ),
    ]
