# Generated by Django 4.2.30 on 2026-08-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_rename_job_descrip_created_a5d3de_idx_jobs_created_7c32a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
