# Generated by Django 4.2.30 on 2026-09-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_jobcandidateassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobcandidateassignment',
            new_name='job_candida_job_id_177a0e_idx',
            old_name='job_cand_job_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobcandidateassignment',
            new_name='job_candida_candida_ca754e_idx',
            old_name='job_cand_cand_idx',
        ),
        migrations.RenameIndex(
            model_name='jobcandidateassignment',
            new_name='job_candida_assigne_0bbd8f_idx',
            old_name='job_cand_assigned_idx',
        ),
    ]
